const login = "//div[@class='only-desktop--2pxYG']//span[contains(text(),'Login')]"
const continueWithMail = "//span[@class = 'email-text--FbASN']"
const imputEmail = "//input[@id='input_email']"
const inputPassword = "//input[@id='input_password']"
const loginButton = "//button[@class='btn--1gFez secondary--Os-e9 background--2lR9B small--1MQ15 gtm-email-login disabled--1OIBt']"
const myAccount = "//span[contains(text(),'My account')]"
